version: '3.8'
 
services:
  web:
    build:
      context: ./book_project
      dockerfile: Dockerfile
    command: gunicorn book_project.wsgi:application --bind 0.0.0.0:8000
    # volumes:
    #   - ./book_project/:/usr/src/app/
    volumes:
        - static_volume:/home/app/web/static
    expose:
      - 8000
    env_file:
      - ./book_project/.env
    depends_on:
      - db
  db:
    image: postgres:14.8
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./book_project/.env

  nginx:
    build: ./nginx
    volumes:
      - static_volume:/home/app/web/static
    ports:
        - 1317:80
    depends_on:
        - web     

volumes:
  postgres_data:
  static_volume:
