version: '3.8'
 
services:
  web:
    container_name: web
    build:
      context: ./backend
      dockerfile: Dockerfile
    command: gunicorn backend.wsgi:application --bind 0.0.0.0:8000
    volumes:
        - static_volume:/home/app/web/static
    expose:
      - 8000
    env_file:
      - ./backend/.env
    depends_on:
      - db
  db:
    image: postgres:14.8
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./backend/.env

  nginx:
    container_name: nginx
    build: ./nginx
    volumes:
      - static_volume:/home/app/web/static
    ports:
        - 1317:80
    depends_on:
        - web     

volumes:
  postgres_data:
  static_volume:
