#!/bin/bash

# DB
echo "DATABASE_URL=$DATABASE_URL" >> .env
echo "DATABASE_DB=$DATABASE_DB" >> .env
echo "DATABASE_USER=$DATABASE_USER" >> .env
echo "DATABASE_PASSWORD=$DATABASE_PASSWORD" >> .env
echo "DATABASE_HOST=$DATABASE_HOST" >> .env
echo "DATABASE_PORT=$DATABASE_PORT" >> .env

echo "POSTGRES_USER=$POSTGRES_USER" >> .env
echo "POSTGRES_PASSWORD=$POSTGRES_PASSWORD" >> .env
echo "POSTGRES_DB=$POSTGRES_DB" >> .env

# Django
echo "SECRET_KEY=$SECRET_KEY" >> .env
echo "ALLOWED_HOSTS=$DJANGO_ALLOWED_HOSTS" >> .env
echo "DEBUG=$DEBUG" >> .env
echo "CSRF_TRUSTED_ORIGINS=$CSRF_TRUSTED_ORIGINS" >> .env